services:

  mariadb-dev:
    image: mariadb:latest
    restart: always
    container_name: mariadb-dev
    environment:
      MARIADB_ROOT_PASSWORD: mariadb123
      MARIADB_DATABASE: urlshortenerdb
      MARIADB_USER: user
      MARIADB_PASSWORD: password_for_url_shortener
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - url-shortener-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  # client:
  #   build:
  #     context: ./ClientApp
  #   ports:
  #     - "3000:80"
  #   restart: always
  #   networks:
  #     - url-shortener-network

  server:
    build:
      context: .
    ports:
      - "5000:8080"
      - "2443:2443"
    depends_on:
      # - client
      - mariadb-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTPS_PORT=2443
    restart: always
    volumes:
      - dpkeys:/var/dpkeys
    networks:
      - url-shortener-network
    command: >
      sh -c "dotnet ef database update &&
             dotnet url_shortener.dll"


networks: 
  url-shortener-network:
    driver: bridge

volumes:
  dpkeys:
  db_data: